# 06 - Métodos de Gauss
Vamos aprender sobre como usar os métodos de Gauss para resolução de sistemas lineares quadráticos.

Crie uma nova branch (versão) do repositório:

```bash
git branch semana6
```

Faça o checkout nessa nova branch:

```bash
git checkout semana6
```

<hr />

## Atividade 1
Escreva os métodos de gauss dentro do arquivo $utils/algoritmos.py$.

In [19]:
import sys
from pathlib import Path

import numpy as np

sys.path.append(str(Path.cwd().parent))
from utils.algoritmos import jacobi, lu, lu_pivot, seidel

A = np.array([
    [1, 1, 1],
    [4, 4, 2],
    [2, 1, -1],
], dtype=float)
B = np.array([1, 2, 0], dtype=float)

P, L, U = lu_pivot(A)
print("Fatoração PA = LU:")
print("P =\n", P)
print("L =\n", L)
print("U =\n", U)
print("\nSolução LU:", lu(A, B))
print("Solução NumPy:", np.linalg.solve(A, B))

A_iterativa = np.array([
    [2, 1, -1],
    [4, 4, 2],
    [1, 1, 1],
], dtype=float)
B_iterativa = np.array([0, 2, 1], dtype=float)
print("\nSolução Jacobi:", jacobi(A_iterativa, B_iterativa, 1000, 1e-8))
print("Solução Gauss-Seidel:", seidel(A_iterativa, B_iterativa, 1000, 1e-8))

Fatoração PA = LU:
P =
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L =
 [[ 1.    0.    0.  ]
 [ 0.5   1.    0.  ]
 [ 0.25 -0.    1.  ]]
U =
 [[ 4.   4.   2. ]
 [ 0.  -1.  -2. ]
 [ 0.   0.   0.5]]

Solução LU: [ 1. -1.  1.]
Solução NumPy: [ 1. -1.  1.]

Solução Jacobi: [ 0.99999996 -0.99999994  0.99999998]
Solução Gauss-Seidel: [ 1. -1.  1.]


Consideramos o seguinte sistema linear:

$$
\begin{cases}
x_1 + x_2 + x_3 = 1\\
4x_1 + 4x_2 + 2x_3 = 2\\
2x_1 + x_2 - x_3 = 0
\end{cases}
$$

Na sua forma matricial, este sistema é escrito como

$$
Ax = b \iff
\begin{bmatrix}
1 & 1 & 1 \\
4 & 4 & 2 \\
2 & 1 & -1
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
=
\begin{bmatrix}
1 \\
2 \\
0
\end{bmatrix}
$$

Podemos resolver em Python usando a biblioteca NumPy.

In [20]:
import numpy as np

A = np.array([
    [1, 1, 1],
    [4, 4, 2],
    [2, 1, -1],
], dtype=float)
B = np.array([1, 2, 0], dtype=float)

print("Matriz A:")
print(A)
print("\nVetor B:")
print(B)
print("\nSolução NumPy x:")
print(np.linalg.solve(A, B))

Matriz A:
[[ 1.  1.  1.]
 [ 4.  4.  2.]
 [ 2.  1. -1.]]

Vetor B:
[1. 2. 0.]

Solução NumPy x:
[ 1. -1.  1.]


Agora, resolva usando os métodos de gauss e compare os resultados.

In [21]:
import sys
from pathlib import Path

import numpy as np

sys.path.append(str(Path.cwd().parent))
from utils.algoritmos import lu

A = np.array([
    [1, 1, 1],
    [4, 4, 2],
    [2, 1, -1],
], dtype=float)
B = np.array([1, 2, 0], dtype=float)

print("Solução NumPy:", np.linalg.solve(A, B))
print("Solução LU:", lu(A, B))

A_iterativa = np.array([
    [2, 1, -1],
    [4, 4, 2],
    [1, 1, 1],
], dtype=float)
B_iterativa = np.array([0, 2, 1], dtype=float)

from utils.algoritmos import jacobi, seidel
print("Solução Jacobi:", jacobi(A_iterativa, B_iterativa, 1000, 1e-8))
print("Solução Gauss-Seidel:", seidel(A_iterativa, B_iterativa, 1000, 1e-8))

Solução NumPy: [ 1. -1.  1.]
Solução LU: [ 1. -1.  1.]
Solução Jacobi: [ 0.99999996 -0.99999994  0.99999998]
Solução Gauss-Seidel: [ 1. -1.  1.]


## Atividade 2
Resolva o seguinte sistema pelo método de Jacobi e Gauss–Seidel:

$$
\begin{cases}
5x_1 + x_2 + x_3 = 50 \\
-x_1 + 3x_2 - x_3 = 10 \\
x_1 + 2x_2 + 10x_3 = -30
\end{cases}
$$

Use como critério de paragem tolerância inferior a $10^{-3}$  
e inicialize com $x^0 = y^0 = z^0 = 0$.

In [22]:
import sys
from pathlib import Path

import numpy as np

sys.path.append(str(Path.cwd().parent))
from utils.algoritmos import jacobi, seidel

A = np.array([
    [5, 1, 1],
    [-1, 3, -1],
    [1, 2, 10],
], dtype=float)
B = np.array([50, 10, -30], dtype=float)

referencia = np.linalg.solve(A, B)
print(f"Solução de referência: {referencia}")

for nome, metodo in (("Jacobi", jacobi), ("Gauss-Seidel", seidel)):
    resultado = metodo(A, B, k=1000, TOL=1e-3)
    residuo = np.linalg.norm(A @ resultado - B, ord=np.inf)
    print(f"{nome}: {resultado}")
    print(f"Resíduo máximo: {residuo:.3e}")

Solução de referência: [10.  5. -5.]
Jacobi: [ 9.99984393  5.00012301 -5.00013019]
Resíduo máximo: 1.212e-03
Gauss-Seidel: [10.00001333  5.00001383 -5.0000041 ]
Resíduo máximo: 7.640e-05


## Atividade 3
Faça uma permutação de linhas no sistema abaixo e resolva pelos métodos de Jacobi e Gauss–Seidel:

$$
\begin{cases}
x_{1} + 10x_{2} + 3x_{3} = 27 \\
4x_{1} + x_{3} = 6 \\
2x_{1} + x_{2} + 4x_{3} = 12
\end{cases}
$$

In [23]:
import sys
from pathlib import Path

import numpy as np

sys.path.append(str(Path.cwd().parent))
from utils.algoritmos import jacobi, seidel

# Permutacao das equacoes: [equacao 2, equacao 1, equacao 3].
# Assim, a matriz fica diagonalmente dominante.
A = np.array([
    [4, 0, 1],
    [1, 10, 3],
    [2, 1, 4],
], dtype=float)
B = np.array([6, 27, 12], dtype=float)

referencia = np.linalg.solve(A, B)
print(f"Solução de referência: {referencia}")

for nome, metodo in (("Jacobi", jacobi), ("Gauss-Seidel", seidel)):
    resultado = metodo(A, B, k=1000, TOL=1e-8)
    residuo = np.linalg.norm(A @ resultado - B, ord=np.inf)
    print(f"{nome}: {resultado}")
    print(f"Resíduo máximo: {residuo:.3e}")

Solução de referência: [1. 2. 2.]
Jacobi: [1. 2. 2.]
Resíduo máximo: 2.056e-08
Gauss-Seidel: [1. 2. 2.]
Resíduo máximo: 1.354e-08


## Atividade 4
O circuito linear da Figura pode ser modelado pelo sistema dado a seguir.  
Escreva esse sistema na forma matricial sendo as tensões $V_1, V_2, V_3, V_4, V_5$ as cinco incógnitas.  
Resolva esse problema quando $V = 127$ e:

- $R_1 = R_2 = R_3 = R_4 = 2$, $R_5 = R_6 = R_7 = 100$ e $R_8 = 50$
- $R_1 = R_2 = R_3 = R_4 = 2$, $R_5 = 50$, $R_6 = R_7 = R_8 = 100$

Sistema de equações:

$$
V_1 = V
$$

$$
\frac{V_1 - V_2}{R_1} + \frac{V_5 - V_2}{R_2} - \frac{V_2}{R_5} = 0
$$

$$
\frac{V_2 - V_3}{R_2} + \frac{V_4 - V_3}{R_3} - \frac{V_3}{R_6} = 0
$$

$$
\frac{V_3 - V_4}{R_3} + \frac{V_5 - V_4}{R_4} - \frac{V_4}{R_7} = 0
$$

$$
\frac{V_4 - V_5}{R_4} - \frac{V_5}{R_8} = 0
$$

![Circuito](https://www.ufrgs.br/reamat/CalculoNumerico/livro-py/main11x.png)

Complete a tabela abaixo representando a solução com **4 algarismos significativos**:

| Caso | $V_1$ | $V_2$ | $V_3$ | $V_4$ | $V_5$ |
|------|-------|-------|-------|-------|-------|
| a    |       |       |       |       |       |
| b    |       |       |       |       |       |

Então, refaça este problema reduzindo o sistema para apenas 4 incógnitas ($V_2, V_3, V_4, V_5$).

In [24]:
import numpy as np

V = 127.0

# Caso a
R1 = R2 = R3 = R4 = 2.0
R5 = R6 = R7 = 100.0
R8 = 50.0

A_a = np.array([
    [1.0, 0.0, 0.0, 0.0, 0.0],
    [1/R1, -(1/R1 + 1/R2 + 1/R5), 0.0, 0.0, 1/R2],
    [0.0, 1/R2, -(1/R2 + 1/R3 + 1/R6), 1/R3, 0.0],
    [0.0, 0.0, 1/R3, -(1/R3 + 1/R4 + 1/R7), 1/R4],
    [0.0, 0.0, 0.0, 1/R4, -(1/R4 + 1/R8)],
], dtype=float)

b_a = np.array([V, 0.0, 0.0, 0.0, 0.0], dtype=float)
sol_a = np.linalg.solve(A_a, b_a)

# Caso b
R5 = 50.0
R6 = R7 = R8 = 100.0

A_b = np.array([
    [1.0, 0.0, 0.0, 0.0, 0.0],
    [1/R1, -(1/R1 + 1/R2 + 1/R5), 0.0, 0.0, 1/R2],
    [0.0, 1/R2, -(1/R2 + 1/R3 + 1/R6), 1/R3, 0.0],
    [0.0, 0.0, 1/R3, -(1/R3 + 1/R4 + 1/R7), 1/R4],
    [0.0, 0.0, 0.0, 1/R4, -(1/R4 + 1/R8)],
], dtype=float)

b_b = np.array([V, 0.0, 0.0, 0.0, 0.0], dtype=float)
sol_b = np.linalg.solve(A_b, b_b)

print("Atividade 4 - Sistema completo")
print("Caso a:", np.round(sol_a, 4))
print("Caso b:", np.round(sol_b, 4))

# Redução para 4 incógnitas: V2, V3, V4, V5
# Equações para as incógnitas restantes, com V1 = V
A_red_a = np.array([
    [1/R1 + 1/R2 + 1/R5, 0.0, 0.0, -1/R2],
    [-1/R2, 1/R2 + 1/R3 + 1/R6, -1/R3, 0.0],
    [0.0, -1/R3, 1/R3 + 1/R4 + 1/R7, -1/R4],
    [0.0, 0.0, 1/R4, -(1/R4 + 1/R8)],
], dtype=float)

b_red_a = np.array([V/R1, 0.0, 0.0, 0.0], dtype=float)
sol_red_a = np.linalg.solve(A_red_a, b_red_a)

R5 = 50.0
R6 = R7 = R8 = 100.0
A_red_b = np.array([
    [1/R1 + 1/R2 + 1/R5, 0.0, 0.0, -1/R2],
    [-1/R2, 1/R2 + 1/R3 + 1/R6, -1/R3, 0.0],
    [0.0, -1/R3, 1/R3 + 1/R4 + 1/R7, -1/R4],
    [0.0, 0.0, 1/R4, -(1/R4 + 1/R8)],
], dtype=float)

b_red_b = np.array([V/R1, 0.0, 0.0, 0.0], dtype=float)
sol_red_b = np.linalg.solve(A_red_b, b_red_b)

print("\nAtividade 4 - Sistema reduzido")
print("Caso a:", np.round(sol_red_a, 4))
print("Caso b:", np.round(sol_red_b, 4))

Atividade 4 - Sistema completo
Caso a: [127.     108.073  100.5113  94.9598  91.3075]
Caso b: [127.     110.5558 104.4854 100.5046  98.5339]

Atividade 4 - Sistema reduzido
Caso a: [110.5558 104.4854 100.5046  98.5339]
Caso b: [110.5558 104.4854 100.5046  98.5339]


## Versionando o código

Submeta a branch para o servidor:

```bash
git add .
git commit -m "Semana 6"
git push origin semana6
```