# 02 - Estruturas de controle
Vamos aprender sobre estruturas de controle, instalação de bibliotecas e geração de gráficos, por meio de atividades práticas.

Crie uma nova branch (versão) do repositório:

```bash
git branch semana2
```

Faça o checkout nessa nova branch:

```bash
git checkout semana2
```

<hr />

## Atividade 1
Faça na linguagem Python uma função que verifica se um número é perfeito.

Um número é perfeito se a soma dos divisores for igual a ele mesmo (ex: 6 = 1 + 2 + 3).

In [1]:
def is_perfect(n: int) -> bool:
    if n < 1:
        return False

    sum_divisors = 0
    for i in range(1, n):
        if n % i == 0:
            sum_divisors += i

    return sum_divisors == n


def main():
    assert is_perfect(6) == True
    assert is_perfect(7) == False
    assert is_perfect(-1) == False


if __name__ == "__main__":
    main()

## Atividade 2
Faça na linguagem Python uma função que calcula o fatorial de um número.

O fatorial de um número é o produto do número por todos os antecessores positivos.

In [2]:
def factorial(n: int) -> int:
    if n < 0:
        raise ValueError("O número deve ser não negativo.")

    result = 1
    i = n
    while i > 1:
        result *= i
        i -= 1

    return result

def main():
    assert factorial(5) == 120
    assert factorial(0) == 1
    try:
        factorial(-1)
    except ValueError as error:
        assert str(error) == "O número deve ser não negativo."

if __name__ == "__main__":
    main()

## Atividade 3
Faça na linguagem Python uma função que verifica se um número é primo.

Um número que só pode ser dividido por um e por ele mesmo.

In [3]:
def is_primo(n: int) -> bool:
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False

    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6

    return True


# demonstração da Atividade 3
print('Atividade 3: verificação de número primo')
for value in [0, 1, 2, 3, 4, 17, 18, 19, -5]:
    print(f'{value} é primo? {is_primo(value)}')

Atividade 3: verificação de número primo
0 é primo? False
1 é primo? False
2 é primo? True
3 é primo? True
4 é primo? False
17 é primo? True
18 é primo? False
19 é primo? True
-5 é primo? False


## Atividade 4
Faça na linguagem Python uma função que calcula a soma dos dígitos.

Caso número negativo, dispare uma mensagem de erro (ex: 123, 1 + 2 + 3 = 6).

In [4]:
def sum_digits(n: int) -> int:
    if n < 0:
        raise ValueError('Número negativo não é permitido.')

    total = 0
    current = n
    while current > 0:
        total += current % 10
        current //= 10

    return total


# demonstração da Atividade 4
print('\nAtividade 4: soma dos dígitos')
for value in [123, 405, 0]:
    print(f'soma dos dígitos de {value} = {sum_digits(value)}')


Atividade 4: soma dos dígitos
soma dos dígitos de 123 = 6
soma dos dígitos de 405 = 9
soma dos dígitos de 0 = 0


## Atividade 5
A partir de agora, vamos usar um ambiente virtual para execução dos nossos códigos.

Em Python, *venv* é um módulo que permite criar ambientes virtuais isolados, fundamentais para manter as dependências de cada projeto separadas e evitar conflitos com outras aplicações:

```bash
python3 -m venv .venv
source .venv/bin/activate
```

Para sair do ambiente, utilize o comando:

```bash
deactivate
```

Instale e importe a biblioteca NumPy, que é fundamental para computação científica em Python, oferecendo suporte para arrays e matrizes multidimensionais, além de uma vasta coleção de funções matemáticas de alto nível para operar eficientemente. Para instalar, utilize o comando:

In [5]:
%pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


Escreva um algoritmo que realize o seguinte produto matricial:

[ [1, 2, 3],  
  [4, 5, 6],  
  [7, 8, 9] ]  

multiplicado por:

[ [11, 12, 13],  
  [14, 15, 16],  
  [17, 18, 19] ]

In [6]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])

C = A.dot(B)

print('Atividade 5: produto matricial')
print('Matriz A:')
print(A)
print('\nMatriz B:')
print(B)
print('\nA x B =')
print(C)

Atividade 5: produto matricial
Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz B:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

A x B =
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


## Versionando o código

Submeta a branch para o servidor:

```bash
git add .
git commit -m "Semana 2"
git push origin semana2
```